# Generated by Django 4.2.7 on 2025-12-19 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория вина',
                'verbose_name_plural': 'Категории вин',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WineColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Цвет вина',
                'verbose_name_plural': 'Цвета вин',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WineSugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Содержание сахара',
                'verbose_name_plural': 'Содержание сахара',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='wines/', verbose_name='Изображение')),
                ('saved', models.BooleanField(default=False, verbose_name='Сохранено')),
                ('volume', models.FloatField(verbose_name='Объем (л)')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('aging', models.IntegerField(verbose_name='Выдержка (лет)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='wine_api.winecategory', verbose_name='Категория')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='wine_api.country', verbose_name='Страна')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='wine_api.producer', verbose_name='Производитель')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='wine_api.region', verbose_name='Регион')),
                ('sugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='wine_api.winesugar', verbose_name='Содержание сахара')),
            ],
            options={
                'verbose_name': 'Вино',
                'verbose_name_plural': 'Вина',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('place', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('price', models.IntegerField(verbose_name='Цена билета')),
                ('available', models.IntegerField(verbose_name='Доступно билетов')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Изображение')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='wine_api.city', verbose_name='Город')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='wine_api.producer', verbose_name='Производитель')),
                ('wine_list', models.ManyToManyField(blank=True, related_name='events', to='wine_api.wine', verbose_name='Список вин')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['date', 'name'],
            },
        ),
    ]
