# Generated by Django 4.2.7 on 2025-12-19 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GrapeVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сорта')),
            ],
            options={
                'verbose_name': 'Сорт винограда',
                'verbose_name_plural': 'Сорта винограда',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='wines/', verbose_name='Изображение')),
                ('volume', models.FloatField(verbose_name='Объем (л)')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('aging', models.IntegerField(verbose_name='Год производства')),
                ('aging_caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание года производства')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вино',
                'verbose_name_plural': 'Вина',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория вина',
                'verbose_name_plural': 'Категории вин',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WineColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Цвет вина',
                'verbose_name_plural': 'Цвета вин',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WineSugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Содержание сахара',
                'verbose_name_plural': 'Содержание сахара',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WineGrapeComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField(help_text='Процентное содержание сорта в вине', verbose_name='Процент содержания')),
                ('grape_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine_api.grapevariety', verbose_name='Сорт винограда')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine_api.wine')),
            ],
            options={
                'verbose_name': 'Содержание сорта винограда в вине',
                'verbose_name_plural': 'Содержание сорта винограда в вине',
            },
        ),
        migrations.AddField(
            model_name='wine',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='wine_api.winecategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='wine',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='wine_api.winecolor', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='wine',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='wine_api.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='wine',
            name='grape_varieties',
            field=models.ManyToManyField(blank=True, related_name='wines', through='wine_api.WineGrapeComposition', to='wine_api.grapevariety'),
        ),
        migrations.AddField(
            model_name='wine',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='wine_api.producer', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='wine',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='wine_api.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='wine',
            name='sugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='wine_api.winesugar', verbose_name='Содержание сахара'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('place', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена билета')),
                ('available', models.IntegerField(blank=True, null=True, verbose_name='Доступно билетов')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Изображение')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='wine_api.city', verbose_name='Город')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='wine_api.producer', verbose_name='Производитель')),
                ('wine_list', models.ManyToManyField(blank=True, related_name='events', to='wine_api.wine', verbose_name='Список вин')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['date', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='winegrapecomposition',
            constraint=models.CheckConstraint(check=models.Q(('percentage__lte', 100)), name='percentage_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='winegrapecomposition',
            constraint=models.UniqueConstraint(fields=('wine', 'grape_variety'), name='unique_wine_grape'),
        ),
    ]
