# Generated by Django 4.2.7 on 2025-12-27 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wine_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя ранга')),
            ],
            options={
                'verbose_name': 'Ранг персоны',
                'verbose_name_plural': 'Ранги персон',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, verbose_name='Никнейм')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('firstname', models.CharField(max_length=255, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='wine_api.persongrade', verbose_name='Ранг')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
                'ordering': ['lastname', 'firstname'],
            },
        ),
    ]
