# Generated by Django 4.2.7 on 2025-12-19 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wine_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrapeVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сорта')),
            ],
        ),
        migrations.AlterField(
            model_name='wine',
            name='aging',
            field=models.IntegerField(verbose_name='Год производства'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='WineGrapeComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField(help_text='Процентное содержание сорта в вине', verbose_name='Процент содержания')),
                ('grape_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine_api.grapevariety')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine_api.wine')),
            ],
        ),
        migrations.AddField(
            model_name='wine',
            name='grape_varieties',
            field=models.ManyToManyField(related_name='wines', through='wine_api.WineGrapeComposition', to='wine_api.grapevariety'),
        ),
        migrations.AddConstraint(
            model_name='winegrapecomposition',
            constraint=models.CheckConstraint(check=models.Q(('percentage__lte', 100)), name='percentage_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='winegrapecomposition',
            constraint=models.UniqueConstraint(fields=('wine', 'grape_variety'), name='unique_wine_grape'),
        ),
    ]
