# Generated by Django 4.2.7 on 2026-01-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_api', '0002_persongrade_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winegrapecomposition',
            name='percentage',
            field=models.PositiveIntegerField(blank=True, help_text='Процентное содержание сорта в вине', null=True, verbose_name='Процент содержания'),
        ),
    ]
