# Generated by Django 4.2.7 on 2026-01-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_api', '0003_alter_winegrapecomposition_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='aging',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год производства'),
        ),
    ]
