# Generated by Django 4.2.7 on 2026-01-10 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_api', '0004_alter_wine_aging'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Время'),
        ),
    ]
