# Generated by Django 4.2.7 on 2026-01-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_api', '0005_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events', to='wine_api.person', verbose_name='Список участников'),
        ),
    ]
