# Generated by Django 4.2.7 on 2026-01-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_api', '0006_event_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(max_length=255, unique=True, verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=255, unique=True, verbose_name='Телефон'),
        ),
    ]
