# Generated by Django 4.2.7 on 2026-01-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_api', '0007_alter_person_nickname_alter_person_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='interested_wines',
            field=models.ManyToManyField(blank=True, related_name='interested_persons', to='wine_api.wine', verbose_name='Вина, которыми интересуется пользователь'),
        ),
    ]
