# Generated by Django 4.2.7 on 2026-01-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_api', '0008_person_interested_wines'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='interested_events',
            field=models.ManyToManyField(blank=True, related_name='interested_persons', to='wine_api.event', verbose_name='События, которыми интересуется пользователь'),
        ),
    ]
