# Generated by Django 4.2.7 on 2026-02-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_api', '0010_person_telegram_id_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='sur_lie_months',
            field=models.IntegerField(blank=True, null=True, verbose_name='Выдержка на осадке (месяцев)'),
        ),
        migrations.AddField(
            model_name='wine',
            name='sur_lie_years',
            field=models.IntegerField(blank=True, null=True, verbose_name='Выдержка на осадке (лет)'),
        ),
    ]
