# Generated by Django 4.2.7 on 2026-03-04 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wine_api', '0011_wine_sur_lie_months_wine_sur_lie_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='grade',
        ),
        migrations.AddField(
            model_name='persongrade',
            name='bonuses',
            field=models.TextField(blank=True, help_text='Описание бонусов, доступных на этом уровне грейда', verbose_name='Бонусы за грейд'),
        ),
        migrations.AddField(
            model_name='persongrade',
            name='next_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_grades', to='wine_api.persongrade', verbose_name='Следующий грейд'),
        ),
        migrations.AddField(
            model_name='persongrade',
            name='required_tastings',
            field=models.IntegerField(default=0, help_text='Минимальное количество посещённых дегустаций для получения этого грейда', verbose_name='Необходимое количество дегустаций'),
        ),
    ]
