# Generated by Django 4.2.7 on 2026-03-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_api', '0012_remove_person_grade_persongrade_bonuses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persongrade',
            name='bonuses',
        ),
        migrations.AddField(
            model_name='persongrade',
            name='description',
            field=models.TextField(blank=True, help_text='Описание грейда', verbose_name='Описание грейда'),
        ),
    ]
