# Generated by Django 4.2.7 on 2026-03-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_api', '0014_add_feature_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_gold_member',
            field=models.BooleanField(default=False, verbose_name='Является золотом членом'),
        ),
    ]
