# Generated by Django 4.2.7 on 2026-03-10 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wine_api', '0015_person_is_gold_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['name'], 'verbose_name': 'Фича по подписке', 'verbose_name_plural': 'Фичи по подпискам'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['lastname', 'firstname'], 'verbose_name': 'Пользователь приложения', 'verbose_name_plural': 'Пользователи приложения'},
        ),
        migrations.AlterModelOptions(
            name='persongrade',
            options={'ordering': ['name'], 'verbose_name': 'Грейд', 'verbose_name_plural': 'Грейды'},
        ),
        migrations.AddField(
            model_name='person',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='wine_api.subscription', verbose_name='Подписка'),
        ),
        migrations.AddField(
            model_name='person',
            name='subscription_starts_at',
            field=models.DateField(blank=True, help_text='Дата, с которой подписка действует для персоны', null=True, verbose_name='Дата начала подписки'),
        ),
    ]
