# Generated by Django 5.2.12 on 2026-03-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_api', '0016_add_person_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='duration',
            field=models.IntegerField(default=1, help_text='Продолжительность подписки в месяцах', verbose_name='Продолжительность (месяцев)'),
        ),
    ]
