# Generated by Django 5.2.12 on 2026-03-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_api', '0017_subscription_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_gold_member',
        ),
        migrations.AddField(
            model_name='event',
            name='is_prime',
            field=models.BooleanField(default=False, verbose_name='Только по платной подписке'),
        ),
        migrations.AddField(
            model_name='wine',
            name='is_prime',
            field=models.BooleanField(default=False, verbose_name='Только по платной подписке'),
        ),
    ]
