# Generated by Django 5.2.12 on 2026-03-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_api', '0018_remove_person_is_gold_member_event_is_prime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(default=0, help_text='Цена', verbose_name='Цена'),
        ),
    ]
